spring:
  application:
    name: edge-service
  cloud:
    config:
      uri: http://localhost:8080
server:
  port: 8090

my:
  greeting: Hello World  From Local

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5


